alter table if exists books drop constraint if exists FKfjixh2vym2cvfj3ufxj91jem7;
drop table if exists authors cascade;
drop table if exists books cascade;
drop sequence if exists authors_SEQ;
drop sequence if exists books_SEQ;
alter table if exists books drop constraint if exists FKfjixh2vym2cvfj3ufxj91jem7;
drop table if exists authors cascade;
drop table if exists books cascade;
drop sequence if exists authors_SEQ;
drop sequence if exists books_SEQ;
alter table if exists books drop constraint if exists FKfjixh2vym2cvfj3ufxj91jem7;
drop table if exists authors cascade;
drop table if exists books cascade;
drop sequence if exists authors_SEQ;
drop sequence if exists books_SEQ;
alter table if exists books drop constraint if exists FKfjixh2vym2cvfj3ufxj91jem7;
drop table if exists authors cascade;
drop table if exists books cascade;
drop sequence if exists authors_SEQ;
drop sequence if exists books_SEQ;
alter table if exists books drop constraint if exists FKfjixh2vym2cvfj3ufxj91jem7;
drop table if exists authors cascade;
drop table if exists books cascade;
drop sequence if exists authors_SEQ;
drop sequence if exists books_SEQ;
alter table if exists books drop constraint if exists FKfjixh2vym2cvfj3ufxj91jem7;
drop table if exists authors cascade;
drop table if exists books cascade;
drop sequence if exists authors_SEQ;
drop sequence if exists books_SEQ;
